### ISSUE TITLE
Toggle Refinement

### ISSUE THREAD

**Issue by iMusicJJ** [algolia/unified-instantsearch-ecommerce#158]
Hi @francoischalifour & Team.

Thanks for the fantastic setup here!

I am having a bit of trouble implementing a Toggle Refinement.

It seems to always add `attribute:undefined` instead of `attribute:true` or `attribute:false` to the request. How is the value to be used in the request extracted from the refinement? That way I can probably manually override it.

Cheers

**Comment by francoischalifour** [comment]
Hey @iMusicJJ! Do you have any code snippet to share?

As a reference, here's the [`ToggleRefinement`](https://www.algolia.com/doc/api-reference/widgets/toggle-refinement/react/) documentation.

**Comment by JapSeyz** [comment]
I figured it out. The issue being that the ToggleRefinement doesn't have a `value` attribute. Which the CurrentRefinements rely upon.

The toggle relies upon `currentRefinement` to calculate its value, rather than a value attribute. But accessing a `value` attribute seems hardcoded into UNI. Which is why it returned undefined for the Toggle.

Simply overloading the attribute solved the issue:

```
function updateValue(val) {
    props.value = val
    refine(val)
  }
```
